Modify do not merge check to pass intead of skip

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -21,12 +21,16 @@ jobs:
           noChangelogLabel: 'O: Skip changelog'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   do-not-merge:
-    if: "contains(github.event.pull_request.labels.*.name, 'O: Requires rebasing')"
     runs-on: ubuntu-slim
     steps:
       - name: Check for label
         run: |
-          echo "Pull request contains a label that prevents the merge."
-          echo "This workflow will now fail."
-          exit 1
+          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'O: Requires rebasing') }}" == "true" ]]; then
+            echo "Pull request contains a label that prevents the merge."
+            echo "This workflow will now fail."
+            exit 1
+          fi
+          echo "No blocking label found."
+          echo "This workflow will now succeed."
